### ISSUE TITLE
SWEEET JESUS YES FINALLY

### ISSUE THREAD

**Issue by pirate** [wg-dashboard/wg-dashboard#10]
<3 ya'll thank you so much for making this. I've wanted a nice wireguard gui for a long time.

I'm going to link it all over the https://github.com/pirate/wireguard-docs

(you can close this once you see it, just wanted to say thanks)

**Comment by erdii** [comment]
Nice! <3

**Comment by erdii** [comment]
@pirate I can't find wg-dashboard on your list. Am I missing something? 🙈

**Comment by pirate** [comment]
No sorry just been busy with a client project and packing for burning man haha, it's tracked here right now https://github.com/pirate/wireguard-docs

You're welcome to submit a PR for the places you think it would go best, otherwise I'll get around to adding it myself when I get back around Sep 5th.

**Comment by erdii** [comment]
Nevermind dude, we'll create a PR :)
Have fun at burning man! 🎉
