### ISSUE TITLE
Pebble a cheaper hosting vps

### ISSUE THREAD

**Issue by elreydetoda** [wg-dashboard/wg-dashboard#12]
So I heard about this vps provider from [Linus Tech Tips](https://youtu.be/9bWA3BNx3A0) (which you can use LTT as a promo code to get 15% off at checkout), and they have plans for vps instances at $1.87 a month https://pebblehost.com/vps under their premium offering, and initially it is 100Mbps, but I recently messaged their support and they said to get it an instance bumped up to 500Mbps all you have to do is.
>Just open a billing ticket and we can get the limit raised for you.

Which is similar in spec and bandwidth to vultr's pricing for their lower tiers. Also, they have hosting in Canada and Europe.

**Disclaimer:** I haven't used them yet, but after learning about how easy it is to increase the bandwidth I am probably going to transfer my algo vpn (wireguard) setup to them to get cheaper hosting.
**Another disclaimer:** I don't have any affiliation with the projects/orgs that I mentioned above (I have done like one contribution to algo), besides that I am a consumer to everything. Just saw you had a _Looking for a cheap VPS?_ section and thought I would mention it.

**Comment by erdii** [comment]
Thank you for your input, we will consider it!
