### ISSUE TITLE
Needs to restart service to make new peers work

### ISSUE THREAD

**Issue by DanialNikbin** [wg-dashboard/wg-dashboard#13]
Hi, When I add a peer from dashboard I have to press the save and restart button to make the peer works. The problem is that when I press that button the wg service restarts and all current connected peers don’t have connection for some seconds. Is it possible to add a peer and make it works without interrupting other connected peers? I just recently moved from a script to your dashboard and I remember on the old script when I add a new peer it wouldn't interrupt other connections. 
Thank you for your great job.

**Comment by erdii** [comment]
Hmm strange... We currently restart the whole interface to update the config. Hence the missing connection.

Can you please provide the old script so I can have a look into their restart mechanism and how ours could be improved?

**Comment by DanialNikbin** [comment]
Yeah of course. 
https://github.com/l-n-s/wireguard-install
This is the script I used to setup wireguard. For adding new peers you have to run this script again.

**Comment by erdii** [comment]
Thank you! :)

It seems that the command: `wg set wg0 peer "$CLIENT_PUBKEY" allowed-ips "$CLIENT_ADDRESS/32"` is used to add the client without restarting the wg0 interface.

@daluf what do you think about "no-restart peer-adding"?

**Comment by erdii** [comment]
Maybe we could even decouple the whole peer-management logic from restarts.

* add
* delete
* en-/disable

**Comment by daluf** [comment]
Great idea! I've added this in the new release (v0.19). Adding, deleting and enabling as well as disabling peers should now work on the fly and do not require a complete restart of the wg0 interface.

Please let us know if there are any issues.
