### ISSUE TITLE
Incorrectly read existing wg0.conf file

### ISSUE THREAD

**Issue by hongquan** [wg-dashboard/wg-dashboard#16]
I already have WireGuard installed and configured as VPN server.

When I install wg-dashboard, it doesn't correctly read and display existing configuration.

For example, my server pubkey is `/m/cR7xfgePNY5Xo0xjmEBPVIzXNZFqJXNtIPQ1CwTU=`, but _wg-dashboard_ displayed `ph7o+zVZV78yMPErK3PaHrJOHeadJ52624QvO2OMUxM=`.

**Comment by daluf** [comment]
wg-dashboard does not read your existing config at all. It comes with its own config management - meaning you can not use your old config and need to re-apply your settings in the dashboard.

**Comment by erdii** [comment]
Or you manually edit the file `server_config.json` and insert your previous config there. But do so on your own risk :P

**Comment by daluf** [comment]
Closed due to inactivity.
