### ISSUE TITLE
Generated wg0.conf should not be world accessible

### ISSUE THREAD

**Issue by erdii** [wg-dashboard/wg-dashboard#17]
From user logs in Issue #15 :

> Sep 05 06:35:15 UKWG wg-quick[16346]: Warning: `/etc/wireguard/wg0.conf' is world accessible

we should make the file readable only to wg-dashboard and wireguard itself.

**Comment by bluecmd** [comment]
Same for `server_config.json`

**Comment by daluf** [comment]
fixed as seen in 88e1850e337671520ae1e4aa23d7005866615a0a
