### ISSUE TITLE
npm vuln. packages

### ISSUE THREAD

**Issue by bluecmd** [wg-dashboard/wg-dashboard#19]
Hi,

I got this quite scary message when installing wg-dashboard:
```
found 33 high severity vulnerabilities in 2514 scanned packages
```

I ran `npm audit fix` which seems to have worked.

Also, consider mentioning that doing the automatic install will end up installing kernel modules and run the software as root. I read the script in advance of running it, and that definitively came as a surprise

**Comment by daluf** [comment]
> found 33 high severity vulnerabilities in 2514 scanned packages

The so called vulnerabilities are coming from a dependency of nunjucks, which has not been updated yet.

> Also, consider mentioning that doing the automatic install will end up installing kernel modules and run the software as root.

Yes, installing a kernel level VPN will install kernel modules. Root access is a requirement as seen in the README, it wouldn't be a requirement if we weren't to use it.

**Comment by daluf** [comment]
nevermind, i fixed it

**Comment by bluecmd** [comment]
Thanks, my comment about the root user was more that the web interface runs as root (as opposed to creating a new user to run as and using e.g. capabilities or sudo to configure wiregaurd).
