### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by tegk** [wg-dashboard/wg-dashboard#2]
Please consider to change the port to 3001 or something as 3000 is already used by Grafana :-)

**Comment by daluf** [comment]
Hello,

the port of the webserver is now configurable ( https://github.com/wireguard-dashboard/wireguard-dashboard/commit/595d3ab7d88a640babf47186ddbb15abaaed3df3 ). With the newest version you can set the desired webserver port in the `server_config.json`.
