### ISSUE TITLE
Enhancement: Download peers as zip

### ISSUE THREAD

**Issue by LaurenceMillward** [wg-dashboard/wg-dashboard#26]
Hi,

Would it be possible to have an option added to the dashboard to download all the created peers as a zip file? WG allows importing of a zip file that contain all the peers.conf files on most, if not all OS's so would be very handy.

Cheers.

**Comment by erdii** [comment]
Hey @LaurenceMillward :)

I'm not entirely sure if I understand your use-case correctly.
You want to export ALL peer.confs in one single zip and import that single zip with ALL peer.confs in a single wireguard peer, right? Wouldn't one config per peer be enough?

**Comment by LaurenceMillward** [comment]
Hey @erdii  

If you download the WG app for android / Windows it gives you the option to either import a peer from a single .conf file, or bulk import multiple .conf files from a single .zip. I'm assuming for people who will potentially have a lot of peers per server. Downloading a lot 1 by 1 and then zipping them up is a rather manual process; just thought i'd be a decent addition to have seeing as WG provides the functionality to bulk import, but the dashboard doesn't allow for bulk export.

**Comment by erdii** [comment]
Sounds reasonable.
I'll consider this when we'll talk about the project roadmap!

**Comment by erdii** [comment]
Thank you for your engangement btw :)
