### ISSUE TITLE
Rebooting server doesn't automatically bring WG up

### ISSUE THREAD

**Issue by LaurenceMillward** [wg-dashboard/wg-dashboard#29]
Manually setting up WG for Ubuntu I run "sudo systemctl enable wg-quick@wg0" so that WG always comes back up automatically after a reboot of the server, is it possible to include this with your install script?

**Comment by daluf** [comment]
This should be already implemented as seen here: https://github.com/wg-dashboard/wg-dashboard/blob/master/install_script.sh#L107

**Comment by erdii** [comment]
@LaurenceMillward did you set up the dashboard via our automated setup or manually? The dashboard itself does not ensure that the service is enabled.
