### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by 101script** [wg-dashboard/wg-dashboard#3]
Debian GNU/Linux 9.9 (stretch)
log console:

root@node-red:~# curl https://raw.githubusercontent.com/team-centric-software/wireguard-dashboard/master/install_script.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5048  100  5048    0     0  92288      0 --:--:-- --:--:-- --:--:-- 93481
net.ipv4.ip_forward = 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11646  100 11646    0     0   110k      0 --:--:-- --:--:-- --:--:--  110k

## Populating apt-get cache...

+ apt-get update
Hit:1 http://deb.debian.org/debian stretch-backports InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://deb.debian.org/debian unstable InRelease
Ign:4 http://mirror.yandex.ru/debian stretch InRelease
Hit:5 http://mirror.yandex.ru/debian stretch Release
Hit:6 https://deb.nodesource.com/node_10.x stretch InRelease
Hit:7 https://download.docker.com/linux/ubuntu bionic InRelease
Reading package lists... Done

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/stretch/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 10.x repo...

+ echo 'deb https://deb.nodesource.com/node_10.x stretch main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_10.x stretch main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Hit:2 http://deb.debian.org/debian stretch-backports InRelease
Hit:3 http://deb.debian.org/debian unstable InRelease
Ign:4 http://mirror.yandex.ru/debian stretch InRelease
Hit:5 http://mirror.yandex.ru/debian stretch Release
Hit:6 https://deb.nodesource.com/node_10.x stretch InRelease
Hit:7 https://download.docker.com/linux/ubuntu bionic InRelease
Reading package lists... Done

## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (11.15.0-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2019-07-10 19:51:18--  https://github.com/team-centric-software/wireguard-dashboard/releases/latest
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/wireguard-dashboard/wireguard-dashboard/releases/latest [following]
--2019-07-10 19:51:18--  https://github.com/wireguard-dashboard/wireguard-dashboard/releases/latest
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/wireguard-dashboard/wireguard-dashboard/releases/tag/v0.14 [following]
--2019-07-10 19:51:19--  https://github.com/wireguard-dashboard/wireguard-dashboard/releases/tag/v0.14
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

-                       [ <=>                ]  69.12K  --.-KB/s    in 0.006s

2019-07-10 19:51:20 (11.3 MB/s) - written to stdout [70778]

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   146    0   146    0     0    635      0 --:--:-- --:--:-- --:--:--   637
100 1299k    0 1299k    0     0   904k      0 --:--:--  0:00:01 --:--:-- 2119k

> bcrypt@3.0.6 install /opt/wireguard-dashboard/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[bcrypt] Success: "/opt/wireguard-dashboard/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
npm WARN wireguard-dashboard@1.0.0 scripts['server'] should probably be scripts['start'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 260 packages from 189 contributors and audited 2514 packages in 13.786s
found 0 vulnerabilities

   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │       New minor version of npm available! 6.7.0 → 6.10.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.10.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Rules updated
Rules updated (v6)
Firewall is active and enabled on system startup
Rule added
Rule added (v6)
Rule added
Rule added (v6)
tar (child): coredns.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

how to fix it?
p.s also, please enable automatic ufw install!

**Comment by daluf** [comment]
Hello,

I am afraid but as of now we currently do not support Debian. The currently only supported operating systems for wireguard-dashboard's install script are Ubuntu 18.04 and Raspbian.

**Comment by daluf** [comment]
Updated the install script to stop running if no supported OS is detected. https://github.com/wireguard-dashboard/wireguard-dashboard/commit/e8704b49c58045ee9483242ead18164afd9f2d53
