### ISSUE TITLE
could not restart wireguard: COULD_NOT_SAVE_WIREGUARD_CONFIG

### ISSUE THREAD

**Issue by n-haddag** [wg-dashboard/wg-dashboard#33]
Hello, 
why I still have this error after clicking **Save & Restart**  or the addition of a new peer
![Screenshot_20191118_175520](https://user-images.githubusercontent.com/39639882/69073204-3bb8e300-0a2d-11ea-8dea-776f34e47802.png)
In my logs file I have an error 500

`[18/Nov/2019:13:36:33 +0000] "POST /api/saveandrestart HTTP/1.1" 500 41 "http://127.0.0.1:3000/" "Mozilla/5.0 (X`
Can you tell me where the problem comes from 

NB: config gets into the file server_config.js and also in wg0.conf but the service remains stopped, I have to restart it in the terminal

**Comment by Hobbabobba** [comment]
i had the same problem. set the dns-setting to port 58210 and it could save and restart.

**Comment by n-haddag** [comment]
@Hobbabobba What do you mean set dns-setting to port 58210?

**Comment by Hobbabobba** [comment]
when i tried to set "port" (your screenshot) to "53" i had the same problem: the service didn´t restart.

**Comment by robertvalik** [comment]
I have port set to 58210 and the same problem.

**Comment by MafiaInc** [comment]
Most likely you do not have ufw installed. I think this UI should not handle firewall rules at all.

**Comment by robertvalik** [comment]
I dont have / use ufw. I was trying to use only the device management but I have given up (as the wg-dashboard forces you to store private keys and there seems not to be a simple way to use existing wg cofiguration).

**Comment by kolosek** [comment]
You might not have the UFW installed prior to installing wg-dashboard. Also, openresolv was missing as well.This is what worked:

sudo apt install openresolv
sudo apt install ufw

You can set ufw rules prior to installing the wg-dashboard. Just run the installer again. It will remove the old installation.
