### ISSUE TITLE
unable to change listen address

### ISSUE THREAD

**Issue by changchichung** [wg-dashboard/wg-dashboard#34]
I want to modify wg-dashboard listen address to LAN ip instead , not only localhost , and I read https://github.com/wg-dashboard/wg-dashboard/issues/5 , but I can not find the string in src/httpServer.js 
```
2019-12-04 10:18:06 [minion@hqs004 wg-dashboard]$ grep "localhost" src/httpServer.js 
2019-12-04 10:21:35 [minion@hqs004 wg-dashboard]$ 
```
as you can see , there's no "localhost" in httpServer.js , so how do I modify the listen address now ?

**Comment by Hobbabobba** [comment]
did you read #32?
