### ISSUE TITLE
[Future Plans] Add Start Date and Expiration Date

### ISSUE THREAD

**Issue by GiannisRallis** [wg-dashboard/wg-dashboard#36]
Hello your project is awasome i installed it yesterday. I hoped it had user expiration date but it hasn't so i suggest to make an automation to block users after expiration date inside peer section

**Comment by robert-hedler** [comment]
> Hello your project is awasome i installed it yesterday. I hoped it had user expiration date but it hasn't so i suggest to make an automation to block users after expiration date inside peer section

It Will be perfect!
