### ISSUE TITLE
Cant Enable DNS over TLS 

### ISSUE THREAD

**Issue by GiannisRallis** [wg-dashboard/wg-dashboard#37]
![image](https://user-images.githubusercontent.com/46003430/71545548-0d67e500-2995-11ea-89fe-7afdc0c36b03.png)

Hello people i installed linux 18.04 to vps server and i cant enable DNS over TlS i used automate script to install dashboard.

**Comment by GiannisRallis** [comment]
I reinstalled server and wg-dashboard and option enabled but when i tried to edit Server settings after saving settings it disabled automatically why that??

**Comment by hellofaduck** [comment]
Same problem here, use it on Ubuntu 18.04 TLS, any thoughts?
