### ISSUE TITLE
Config of peer not valid

### ISSUE THREAD

**Issue by tegk** [wg-dashboard/wg-dashboard#4]
Generated config by the dashboard is not valid when using wg-quick.

```
[#] ip link add vl type wireguard
[#] wg setconf vl /dev/fd/63
Name or service not known: `:58210'
Configuration parsing error
[#] ip link delete dev vl

```

(I used X to censor data)
```
[Interface]
Address = 1X.XX.XX.X/24
PrivateKey = XXXXXXXXXXXXXX87pWEA3c0N+gp0/GzUk=
DNS = 10.13.37.1

[Peer]
PublicKey = XXXXXXXXXXXXXXXkJMpPAhEwlHjBcQPqcXU=
Endpoint = :58210
AllowedIPs = 0.0.0.0/0

# This is for if you're behind a NAT and
# want the connection to be kept alive.
PersistentKeepalive = 25

```

**Comment by mattlewis53** [comment]
Looks like there is only a port specified (`:58210`) for the `Endpoint =` This should be an IP address or hostname followed by the port, ie: `Endpoint = 10.0.0.1:58210`

Not sure why the config is being created without an endpoint specified but that certainly looks to be your issue.

**Comment by tegk** [comment]
Thanks, putting in the IP resolved this.
