### ISSUE TITLE
Dns over Tls can't enable after disable

### ISSUE THREAD

**Issue by thinkopensource** [wg-dashboard/wg-dashboard#41]
Hi

Check options I discover how after disable DNS over TLS using button I can't re-enable again, because appears button moved but not text field of file. When you saves and reload appears disabled again.

**Comment by thinkopensource** [comment]
Seems that problem is when dashboard edit wg0.conf. After to change manually this field works again.

**Comment by daluf** [comment]
Hi, thanks for reporting. We will fix this issue in the upcoming rewrite.
