### ISSUE TITLE
Downloading peer as client_config_**** is not compatible with wireguard Android import

### ISSUE THREAD

**Issue by RawSlugs** [wg-dashboard/wg-dashboard#42]
_ underscores are not compatible with wireguard Android create by file, need to rename the file each time.

(Files are also downloading .conf.txt not sure if that's chrome on mobile or that how it's being served - have not tried on desktop yet)

**Comment by daluf** [comment]
Thanks for reporting. I will make sure to fix this in the upcoming rewrite.

**Comment by RawSlugs** [comment]
Did some more testing, the underscores are compatible but conf files can't me more than 15 characters

**Comment by daluf** [comment]
Interesting, maybe we should just strip the config file in the future to be no longer than 15 chars?

**Comment by erdii** [comment]
I think that we can completely strip `client_config_` from the filename

**Comment by linucksrox** [comment]
I don't see a way to contribute issues to the Android client (mirror only on Github, and the official repo doesn't seem to have any bug tracking capabilities). But shouldn't this also be addressed in the Android app?

**Comment by RawSlugs** [comment]
It seams more like a limitation that shouldn't be there than a bug...

**Comment by linucksrox** [comment]
I agree, it does seem like an arbitrary limitation because the Android system can definitely handle more than 15 characters. You don't have to call it a bug, but either way there should be a way to suggest that this be "corrected" but I can't find a good way to contribute that information to the Android Wireguard project.

**Comment by RawSlugs** [comment]
It has already been reported to wireguard (similar issue)
https://lore.kernel.org/wireguard/CAD14+f2_Ko5zZvZ3jh3XzckXALRER1vpc6OyJtZ7p7=BPqH-1Q@mail.gmail.com/

Which I from bug 12) https://docs.google.com/document/u/0/d/15i0Z750eL_OlUyrypUFLF7Hoi5eoF-dTFWj-Rs4RXGI/mobilebasic


Android Todo list
https://www.wireguard.com/todo/

Seams like the only way to report something is to email them

**Comment by linucksrox** [comment]
Thanks for that information, now I know where to look!
