### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by Nico640** [wg-dashboard/wg-dashboard#43]
Hi,

Are there any plans on adding IPv6 support? 
It's hard to set up manually because wg-dashboard keeps overwriting the wg0.conf, but IPv6 does seem to work with some config changes. 

Example IPv6 server config:

```[Interface]
Address = 10.13.37.1/24,fd10:37:37::1/64
PrivateKey = REDACTED
ListenPort = 58210
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE; ip6tables -A FORWARD -i %i -j ACCEPT; ip6tables -A FORWARD -o %i -j ACCEPT; ip6tables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE; ip6tables -D FORWARD -i %i -j ACCEPT; ip6tables -D FORWARD -o %i -j ACCEPT; ip6tables -t nat -D POSTROUTING -o ens3 -j MASQUERADE
SaveConfig = false

[Peer]
        # client
        PublicKey = REDACTED
        AllowedIPs = 10.13.37.2/32,fd10:37:37::2/128
```

<br/>
Example IPv6 client config:

```[Interface]
PrivateKey = REDACTED
Address = 10.13.37.2/24, fd10:37:37::2/64
DNS = 10.13.37.1

[Peer]
PublicKey = REDACTED
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = REDACTED
PersistentKeepalive = 25
```

Also, net.ipv6.conf.all.forwarding=1 has to be set in the sysctl.conf

**Comment by daluf** [comment]
Hi,

adding IPv6 support is essential in our days of the internet. I will make sure to add this in the coming rewrite.

**Comment by hardypt** [comment]
is there any estimated date to get ipv6 working via wg dashboard?

thanks and very nice project! congratz!!

**Comment by revilo951** [comment]
Can't wait for IPv6 implementation, and thanks for an already-great piece of software. :)
