### ISSUE TITLE
reboot

### ISSUE THREAD

**Issue by rigas40** [wg-dashboard/wg-dashboard#45]
after reboot server wireguard dont run auto start automatic?

**Comment by RawSlugs** [comment]
Did you manually install it? Check the status of the service.

**Comment by rigas40** [comment]
i install with curl script

everytime i reboot vps i need go to dashboard and save restart
also
is missing in script check if have ufw
 sudo apt-get install ufw

**Comment by RawSlugs** [comment]
systemctl enable wg-quick@wg0
