### ISSUE TITLE
send by e-mail conf file and QR Code

### ISSUE THREAD

**Issue by robert-hedler** [wg-dashboard/wg-dashboard#47]
Hi, good morning. You did an amazing project, congratulations!
I would like to know if it will be possible to put a send email button to send an email to the peer containing the conf file and QRcode? I found this very useful. The button could be located on the side of these ones:
![image](https://user-images.githubusercontent.com/15235781/77847777-fdc78a80-7195-11ea-8143-3970586efece.png)

What do you think?

Best regards,

**Comment by daluf** [comment]
Hi, generally speaking this is a neat idea. Though, this is currently out of scope, as we don't want to additionally maintain an SMTP server and their settings in WG-Dashboard.
