### ISSUE TITLE
how to access dashboard remotely?

### ISSUE THREAD

**Issue by 101script** [wg-dashboard/wg-dashboard#5]
hi, i installed dashboard, all ok, but i want to open access from outside, in ufw i open port 3000, but, it's not accessible, which configuration need to make, to have access not only from localhost?

**Comment by Artiik373** [comment]
Currently this feature is not available due to security reasons.

**Comment by 101script** [comment]
> 
> 
> Currently this feature is not available due to security reasons.

i will make first autentification with nginix, please, what changes i need to do, to open it from outside

**Comment by Artiik373** [comment]
> > Currently this feature is not available due to security reasons.
> 
> i will make first autentification with nginix, please, what changes i need to do, to open it from outside

I am not sure, but i think you need to open `httpServer.js`, go to line 685 and change `app.listen(state.config.port, "localhost", cb);` to `app.listen(state.config.port, cb);`. Don't forget to open the port in the firewall.

Good luck!

**Comment by 101script** [comment]
thanks, i will try. best regards

**Comment by 101script** [comment]
hi, as i say, you make some changes in httpServer.js, so my hack (sed -i 's/app.listen(state.config.port, "localhost", cb);/app.listen(state.config.port, cb);/g' /opt/wireguard-dashboard/src/httpServer.js)
does now working anymore...where is located now app.listen(state.config.port, "localhost", cb); ?
best regards

**Comment by daluf** [comment]
Hi, it is still located in the same file (`httpServer.js`), but instead of line 685 it is now located at line 818.

**Comment by 101script** [comment]
hi, yes, as i say you removed localhost, so, from now dashboard will be accessible from internet!, thanks
