### ISSUE TITLE
wireguard does not working if public host/ip not set

### ISSUE THREAD

**Issue by ghost** [wg-dashboard/wg-dashboard#6]
hi, i installed wireguard dashboard on second server, but if i not set public ip, other computer can't connect to wireguard server, so it's not problem to set it manually, but, some people, does not know why wireguard not working. maybe to do automatic set it?
best regards.
![anF4WS5O32](https://user-images.githubusercontent.com/20506433/62715127-8d9ea580-ba08-11e9-9d34-aca6edf5d25e.png)

**Comment by daluf** [comment]
Hi,

there is already functionality for the Public Host / IP to be set automatically. The problem is that it only works with the network adapter `eth0`.
