### ISSUE TITLE
Install command is different in the readme to the script

### ISSUE THREAD

**Issue by IonicEcko** [wg-dashboard/wg-dashboard#7]
The install command in the readme references wg-dashboard. The actual location is wireguard-dashboard.

**Comment by IonicEcko** [comment]
I just noticed that it looks like when you renamed everything in your commit an hour ago you missed a bit... It looks like 

`https://raw.githubusercontent.com/team-centric-software/wg-dashboard/master/install_script.sh`

Should be:

`https://raw.githubusercontent.com/wg-dashboard/wg-dashboard/master/install_script.sh`

**Comment by daluf** [comment]
Hi,

thank you for your interest in contributing to wg-dashboard. We already fixed this issue in the README.md aswell as in the install_script.sh.
